/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowRightIcon: typeof import('./src/components/ui/icons/ArrowRightIcon.vue')['default']
    AuthView: typeof import('./src/components/pages/AuthView.vue')['default']
    DashboardNumber: typeof import('./src/components/ui/widgets/DashboardNumber.vue')['default']
    DownloadRealtyReport: typeof import('./src/components/ui/widgets/DownloadRealtyReport.vue')['default']
    DropdownIcon: typeof import('./src/components/ui/icons/DropdownIcon.vue')['default']
    EmptyLayout: typeof import('./src/components/layout/EmptyLayout.vue')['default']
    HeaderNavigationItem: typeof import('./src/components/ui/header/HeaderNavigationItem.vue')['default']
    HeaderNotificationsPopup: typeof import('./src/components/ui/header/HeaderNotificationsPopup.vue')['default']
    HeaderUserPopup: typeof import('./src/components/ui/header/HeaderUserPopup.vue')['default']
    HomeView: typeof import('./src/components/pages/HomeView.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpace: typeof import('naive-ui')['NSpace']
    RealtyEditAddView: typeof import('./src/components/pages/RealtyEditAddView.vue')['default']
    RealtyFieldsView: typeof import('./src/components/ui/realty/RealtyFieldsView.vue')['default']
    RealtyRegistryView: typeof import('./src/components/pages/RealtyRegistryView.vue')['default']
    RealtySection: typeof import('./src/components/ui/realty/RealtySection.vue')['default']
    ReturnToHomeBtn: typeof import('./src/components/ui/widgets/ReturnToHomeBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchAdvancedFilters: typeof import('./src/components/ui/search/SearchAdvancedFilters.vue')['default']
    SearchPanel: typeof import('./src/components/ui/search/SearchPanel.vue')['default']
    SearchPanelFilters: typeof import('./src/components/ui/search/SearchPanelFilters.vue')['default']
    SearchPanelInput: typeof import('./src/components/ui/search/SearchPanelInput.vue')['default']
    SearchPlaceholderIcon: typeof import('./src/components/ui/icons/SearchPlaceholderIcon.vue')['default']
    SettingsIcon: typeof import('./src/components/ui/icons/SettingsIcon.vue')['default']
    TaskByRealtyView: typeof import('./src/components/pages/TaskByRealtyView.vue')['default']
    TasksRegistryView: typeof import('./src/components/pages/TasksRegistryView.vue')['default']
    UpcomingEvents: typeof import('./src/components/ui/widgets/UpcomingEvents.vue')['default']
    UserIcon: typeof import('./src/components/ui/icons/UserIcon.vue')['default']
  }
}
