version: "3.9"

services:
  client:
    container_name: client
    image: siailyadev/ooc-hack-client:latest
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  strapi-service:
    container_name: strapi-service
    build:
      context: service
      dockerfile: dev.Dockerfile
    env_file:
      - service/.env
    volumes:
      - ./service/config:/opt/app/config
      - ./service/src:/opt/app/src
      - ./service/package.json:/opt/package.json
      - ./service/yarn.lock:/opt/yarn.lock
      - ./service/.env:/opt/app/.env
      - ./service/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    depends_on:
      - strapi-database

  strapi-database:
    container_name: strapi-database
    restart: unless-stopped
    image: postgres:14-alpine3.17
    env_file:
      - service/.env
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'

  server:
    container_name: server
    image: philipoff/ooc-hack-server:latest
    restart: always
    ports:
      - "3001:3001"
    environment:
      STRAPI_URL:
      STRAPI_LOGIN:
      STRAPI_PASSWORD:
    depends_on:
      - strapi-service


volumes:
  strapi-data: