version: "3.9"

services:
  strapi-service:
    container_name: strapi-service
    build:
      context: service
      dockerfile: dev.Dockerfile
    env_file:
      - service/.env
    volumes:
      - ./service/config:/opt/app/config
      - ./service/src:/opt/app/src
      - ./service/package.json:/opt/package.json
      - ./service/yarn.lock:/opt/yarn.lock
      - ./service/.env:/opt/app/.env
      - ./service/public/uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    depends_on:
      - strapi-database

  strapi-database:
    container_name: strapi-database
    restart: unless-stopped
    image: postgres:14-alpine3.17
    env_file:
      - service/.env
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'


volumes:
  strapi-data: