version: "3.9"

services:
  client:
    container_name: client
    image: siailyadev/ooc-hack-client:latest
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production

  strapi-service:
    container_name: strapi-service
    image: siailyadev/ooc-hack-strapi-service:0.0.1
    environment:
      HOST:
      PORT:
      APP_KEYS:
      API_TOKEN_SALT:
      ADMIN_JWT_SECRET:
      JWT_SECRET:
      TRANSFER_TOKEN_SALT:
      DATABASE_CLIENT:
      DATABASE_HOST:
      DATABASE_PORT:
      DATABASE_NAME:
      DATABASE_USERNAME:
      DATABASE_PASSWORD:
      DATABASE_SSL:
    volumes:
      - strapi-uploads:/opt/app/public/uploads
    ports:
      - '1337:1337'
    depends_on:
      - strapi-database

  strapi-database:
    container_name: strapi-database
    restart: unless-stopped
    image: postgres:14-alpine3.17
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - strapi-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'


volumes:
  strapi-data:
  strapi-uploads: